codecov:
  require_ci_to_pass: yes

coverage:
  precision: 5
  round: nearest
  range: "5...100"
  status:
    project:
      default:
        target: auto            # [auto,<number>] minimum coverage ratio that the commit must meet
        threshold: 3%           # [<number>] allow the coverage to drop by X%
        base: auto              # [auto,pr,parent] Designate the target to compare against.
        paths:
          - "src"
      components:
        target: auto
        threshold: 3%
        base: auto
        paths:
          - "src/components"
      pages:
        target: auto
        threshold: 3%
        base: auto
        paths:
          - "src/pages"
      templates:
        target: auto
        threshold: 3%
        base: auto
        paths:
          - "src/templates"
      typescript:
        target: auto
        threshold: 3%
        base: auto
        paths:
          - "src/typescript"
    patch:
      default:
        target: 70
        threshold: 0%
        base: auto
        paths:
          - "src"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true
