version: 2.1

orbs:
  node: circleci/node@2.0.1

parameters:
  node-version:
    type: string
    default: "12.16"

jobs:
  testing:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - install-packages:
          cache-version: v1
          cache-key: yarn.lock
          pkg-manager: yarn
          with-cache: true
      - run:
          name: Testing
          command: yarn test
  linting:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - install-packages:
          cache-version: v1
          cache-key: yarn.lock
          pkg-manager: yarn
          with-cache: true
      - run:
          name: Execute eslint
          command: yarn lint

workflows:
  testing-and-checking-code-style:
    jobs:
      - testing
      - linting
