version: 2.1

orbs:
  node: circleci/node@2.0.1

parameters:
  node-version:
    type: string
    default: "12.16"

jobs:
  testing:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - node/install-packages:
          cache-version: v1
          cache-key: yarn.lock
          pkg-manager: yarn
          with-cache: true
          include-branch-in-cache-key: false
      - run:
          name: Testing
          command: yarn test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: "reports/junit"
      - store_test_results:
          path: reports

  linting:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - node/install-packages:
          cache-version: v1
          cache-key: yarn.lock
          pkg-manager: yarn
          with-cache: true
          include-branch-in-cache-key: false
      - run:
          name: Execute eslint
          command: yarn lint:ci
      - store_test_results:
          path: reports

workflows:
  testing-and-checking-code-style:
    jobs:
      - testing
      - linting
