version: 2.1

orbs:
  node: circleci/node@2.0.1
  cypress: cypress-io/cypress@1.19.1
  sonarcloud: sonarsource/sonarcloud@1.0.1

parameters:
  node-version:
    type: string
    default: "12.16"

jobs:
  testing:
    docker:
      - image: cimg/node:<< pipeline.parameters.node-version >>
        environment:
          CODE_COVERAGE: "true"
    steps:
      - checkout
      - node/install-packages:
          cache-version: v1
          cache-key: yarn.lock
          pkg-manager: yarn
          with-cache: true
          include-branch-in-cache-key: false
      - run:
          name: Execute eslint
          command: yarn lint:ci
      - run:
          name: Execute Jest testing
          command: yarn test:ci
      - sonarcloud/scan:
          cache_version: 1
      - store_test_results:
          name: Collect junit reports
          path: reports
      - store_artifacts:
          name: Collect coverage reports
          path: coverage/lcov-report
          destination: coverage
      - persist_to_workspace:
          root: ~/
          paths:
            - reports
            - coverage

workflows:
  main:
    jobs:
      - testing
      - cypress/install:
          requires:
            - testing
          post-checkout:
            - attach_workspace:
                at: ~/
          yarn: true
          cache-key: 'v1-dependencies-{{ checksum "yarn.lock" }}'
          build: yarn build:website
      - cypress/run:
          requires:
            - cypress/install
          start: yarn serve
          wait-on: "http://localhost:9000"
          cache-key: 'v1-dependencies-{{ checksum "yarn.lock" }}'
          store_artifacts: true
          attach-workspace: true
          record: true
          yarn: true
          browser: electron
          post-steps:
            - store_artifacts:
                name: Collect coverage reports
                path: cypress-coverage/lcov-report
                destination: coverage
            - store_test_results:
                name: Collect test reports
                path: reports
