#!/usr/bin/env bash
# shellcheck disable=SC1000

# generate by create-script-file v4.0.1
# link (https://github.com/Template-generator/create-script-file/tree/v4.0.1)

# set -x #DEBUG - Display commands and their arguments as they are executed.
# set -v #VERBOSE - Display shell input lines as they are read.
# set -n #EVALUATE - Check syntax of the script but don't execute.

# paramater: [trace]

export filename="$(basename "${BASH_SOURCE[0]}")"

set_options() {
  local array=()
  for i in "$@"; do
    if [[ $i =~ "trace" ]]; then
      array+=("--open-tracing-config-file" "node_modules/gatsby/dist/utils/tracer/jaeger-local.js")
    else
      array+=("$i")
    fi
  done

  export OPTIONS=("${array[@]}")
}

execute_command() {
  yarn gatsby build "$@"
}

start_command "$@"
