style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/kamontat/kamontat
options:
  commits:
    filters:
      Type:
        - feat
        - impr
        - perf
        - fix
        - chore
  commit_groups:
    title_maps:
      feat: 1. Feature
      impr: 2. Improvement
      perf: 3. Performance
      fix: 4. Fixes Bug
      chore: 5. Technical
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  issues:
    prefix:
      - "#"
  notes:
    keywords:
      - BREAKING CHANGE
